INSERT INTO school
(SCHOOL_ID,
SCHOOL_NAME,
FIRST_DEADLINE,
SECOND_DEADLINE,
THIRD_DEADLINE,
FORTH_DEADLINE,
AVG_GMAT,
AVG_TOEFL,
MEMO)
VALUES
(1,'Harvard Business School',null,null,null,null,0,0,null),
(2,'Stanford Graduate School of Business',null,null,null,null,0,0,null),
(3,'University of Pennsylvania: Wharton',null,null,null,null,0,0,null),
(4,'London Business School',null,null,null,null,0,0,null),
(5,'Columbia Business School',null,null,null,null,0,0,null),
(6,'Insead',null,null,null,null,0,0,null),
(7,'Iese Business School',null,null,null,null,0,0,null),
(8,'Hong Kong T Business School',null,null,null,null,0,0,null),
(9,'MIT: Sloan',null,null,null,null,0,0,null),
(10,'University of Chicago: Booth',null,null,null,null,0,0,null),
(11,'IE Business School',null,null,null,null,0,0,null),
(12,'University of California at Berkeley: Haas',null,null,null,null,0,0,null),
(13,'Northwestern University: Kellogg',null,null,null,null,0,0,null),
(14,'Yale School of Management',null,null,null,null,0,0,null),
(15,'Ceibs',null,null,null,null,0,0,null),
(16,'Dartmouth College: Tuck',null,null,null,null,0,0,null),
(17,'University of Cambridge: Judge',null,null,null,null,0,0,null),
(18,'Duke University: Fuqua',null,null,null,null,0,0,null),
(19,'IMD',null,null,null,null,0,0,null),
(20,'New York University: Stern',null,null,null,null,0,0,null),
(21,'HEC Paris',null,null,null,null,0,0,null),
(22,'Esade Business School',null,null,null,null,0,0,null),
(23,'UCLA: Anderson',null,null,null,null,0,0,null),
(24,'University of Oxford: Sa?d',null,null,null,null,0,0,null),
(25,'Cornell University: Johnson',null,null,null,null,0,0,null),
(26,'n Institute of Management, Ahmedabad',null,null,null,null,0,0,null),
(27,'CUHK Business School',null,null,null,null,0,0,null),
(28,'Warwick Business School',null,null,null,null,0,0,null),
(29,'Manchester Business School',null,null,null,null,0,0,null),
(30,'University of Michigan: Ross',null,null,null,null,0,0,null),
(31,'University of Hong Kong',null,null,null,null,0,0,null),
(32,'Nanyang Business School',null,null,null,null,0,0,null),
(33,'Rotterdam School of Management, Erasmus University',null,null,null,null,0,0,null),
(34,'n School of Business',null,null,null,null,0,0,null),
(35,'University of Virginia: Darden',null,null,null,null,0,0,null),
(36,'National University of Business School',null,null,null,null,0,0,null),
(37,'Rice University: Jones',null,null,null,null,0,0,null),
(38,'Cranfield School of Management',null,null,null,null,0,0,null),
(39,'SDA Bocconi',null,null,null,null,0,0,null),
(40,'City University: Cass',null,null,null,null,0,0,null),
(41,'Georgetown University: McDonough',null,null,null,null,0,0,null),
(42,'Imperial College Business School',null,null,null,null,0,0,null),
(43,'Carnegie Mellon: Tepper',null,null,null,null,0,0,null),
(44,'University of Illinois at Urbana-Champaign',null,null,null,null,0,0,null),
(45,'University of North Carolina: Kenan-Flagler',null,null,null,null,0,0,null),
(46,'University of Toronto: Rotman',null,null,null,null,0,0,null),
(47,'University of Texas at Austin: McCombs',null,null,null,null,0,0,null),
(48,'Australian Graduate School of Management (AGSM)',null,null,null,null,0,0,null),
(49,'Emory University: Goizueta',null,null,null,null,0,0,null),
(50,'University of Maryland: Smith',null,null,null,null,0,0,null),
(51,'Sungkyunkwan University SKK GSB South',null,null,null,null,0,0,null),
(52,'York University: Schulich',null,null,null,null,0,0,null),
(53,'Vanderbilt University: Owen',null,null,null,null,0,0,null),
(54,'Washington University: Olin',null,null,null,null,0,0,null),
(55,'na University: Kelley',null,null,null,null,0,0,null),
(56,'University of California at Irvine: Merage',null,null,null,null,0,0,null),
(57,'Hult International Business School',null,null,null,null,0,0,null),
(58,'University of British Columbia: Sauder',null,null,null,null,0,0,null),
(59,'University of Rochester: Simon',null,null,null,null,0,0,null),
(60,'Georgia Institute of Technology: Scheller',null,null,null,null,0,0,null),
(61,'The Lisbon MBA Portugal',null,null,null,null,0,0,null),
(62,'Michigan State University: Broad',null,null,null,null,0,0,null),
(63,'Melbourne Business School',null,null,null,null,0,0,null),
(64,'Tilburg University, TiasNimbas',null,null,null,null,0,0,null),
(65,'University College Dublin: Smurfit Ireland',null,null,null,null,0,0,null),
(66,'Coppead Brazil',null,null,null,null,0,0,null),
(67,'Peking University: Guanghua',null,null,null,null,0,0,null),
(68,'Purdue University: Krannert',null,null,null,null,0,0,null),
(69,'Mannheim Business School',null,null,null,null,0,0,null),
(70,'Texas A & M University: Mays',null,null,null,null,0,0,null),
(71,'Lancaster University Management School',null,null,null,null,0,0,null),
(72,'University of Bath School of Management',null,null,null,null,0,0,null),
(73,'Ohio State University: Fisher',null,null,null,null,0,0,null),
(74,'University of Cape Town GSB',null,null,null,null,0,0,null),
(75,'University of Iowa: Tippie',null,null,null,null,0,0,null),
(76,'McGill University: Desautels',null,null,null,null,0,0,null),
(77,'Pennsylvania State University: Smeal',null,null,null,null,0,0,null),
(78,'University of Western Ontario: Ivey',null,null,null,null,0,0,null),
(79,'University of Washington: Foster',null,null,null,null,0,0,null),
(80,'Babson College: Olin',null,null,null,null,0,0,null),
(81,'Tulane University: Freeman',null,null,null,null,0,0,null),
(82,'University of St Gallen',null,null,null,null,0,0,null),
(83,'University of Southern California: Marshall',null,null,null,null,0,0,null),
(84,'George Washington University',null,null,null,null,0,0,null),
(85,'Vlerick Business School',null,null,null,null,0,0,null),
(86,' University Business School South',null,null,null,null,0,0,null),
(87,'Arizona State University: Carey',null,null,null,null,0,0,null),
(88,'University of Strathclyde Business School',null,null,null,null,0,0,null),
(89,'Fudan University School of Management',null,null,null,null,0,0,null),
(90,'Incae Business School',null,null,null,null,0,0,null),
(91,'Wisconsin School of Business',null,null,null,null,0,0,null),
(92,'EMLyon Business School',null,null,null,null,0,0,null),
(93,'Boston College: Carroll',null,null,null,null,0,0,null),
(94,'Case Western Reserve University: Weatherhead',null,null,null,null,0,0,null),
(95,'University of California, San Diego: Rady',null,null,null,null,0,0,null),
(96,'Boston University School of Management',null,null,null,null,0,0,null),
(97,'College of William and Mary: Mason',null,null,null,null,0,0,null),
(98,'SMU: Cox',null,null,null,null,0,0,null),
(99,'University of South Carolina: Moore',null,null,null,null,0,0,null),
(100,'University of Alberta',null,null,null,null,0,0,null)