CREATE TABLE `client` (
  `CLIENT_ID` int(11) NOT NULL,
  `LAST_NAME` varchar(45) DEFAULT NULL,
  `FIRST_NAME` varchar(45) DEFAULT NULL,
  `MIDDLE_NAME` varchar(45) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(45) DEFAULT NULL,
  `WORK_PLACE` varchar(1000) DEFAULT NULL,
  `SPONSORED_FLG` int(11) DEFAULT NULL,
  `UNIVERSITY_NAME` varchar(45) DEFAULT NULL,
  `UNIVERSITY_MAJOR` varchar(45) DEFAULT NULL,
  `UNIVERSITY_DEGREE` varchar(45) DEFAULT NULL,
  `UNIVERSITY_GPA` double DEFAULT NULL,
  `ACADEMIC_AWARDS_FLG` int(11) DEFAULT NULL,
  `PUBLICATION_FLG` int(11) DEFAULT NULL,
  `STUDIED_ABROAD_FLG` int(11) DEFAULT NULL,
  `STUDIED_ABROAD_PLACE` varchar(45) DEFAULT NULL,
  `USE_ENGLISH_AT_WORK_FLG` int(11) DEFAULT NULL,
  `FUTURE_GOAL` varchar(2000) DEFAULT NULL,
  `CLIENT_MEMO` varchar(4000) DEFAULT NULL,
  `COUNSELOR_MEMO` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`CLIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Manage Info Unique to Client';


CREATE TABLE `client_gmat` (
  `CLIENT_ID` int(11) NOT NULL,
  `SCORE_NO` int(11) NOT NULL DEFAULT '0',
  `TEST_DATE` date DEFAULT NULL,
  `TOTAL` int(11) DEFAULT NULL,
  `VERBAL` int(11) DEFAULT NULL,
  `MATH` int(11) DEFAULT NULL,
  `AWA` int(11) DEFAULT NULL,
  `INTEGRATED_REASONING` int(11) DEFAULT NULL,
  `MEMO` varchar(5000) DEFAULT NULL,
  PRIMARY KEY (`CLIENT_ID`,`SCORE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Manage Info About Client''s GMAT Score';


CREATE TABLE `client_school_map` (
  `CLIENT_ID` int(11) NOT NULL,
  `SCHOOL_ID` int(11) NOT NULL,
  `PERSONAL_RANK` int(11) DEFAULT NULL,
  `ROUND` varchar(45) DEFAULT NULL,
  `RESULT` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CLIENT_ID`,`SCHOOL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Manage Relation between Client and School';


CREATE TABLE `client_toefl` (
  `CLIENT_ID` int(11) NOT NULL,
  `SCORE_NO` int(11) NOT NULL,
  `TOTAL` int(11) DEFAULT NULL,
  `TEST_DATE` date DEFAULT NULL,
  `READING` int(11) DEFAULT NULL,
  `LISTENING` int(11) DEFAULT NULL,
  `SPEAKING` int(11) DEFAULT NULL,
  `WRITING` int(11) DEFAULT NULL,
  `MEMO` varchar(5000) DEFAULT NULL,
  PRIMARY KEY (`CLIENT_ID`,`SCORE_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Manage Info About Client''s TOEFL Score';


CREATE TABLE `counseling` (
  `CLIENT_ID` int(11) NOT NULL,
  `SEQ` int(11) NOT NULL,
  `COUNSELING_TYPE` int(11) DEFAULT NULL,
  `TIME` int(11) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `CONTENT_TYPE` varchar(200) DEFAULT NULL,
  `MEMO` varchar(5000) DEFAULT NULL,
  `NEXT_ACTION` varchar(5000) DEFAULT NULL,
  `APP_STATUS` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`CLIENT_ID`,`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Manage Info. About Counseling';


CREATE TABLE `school` (
  `SCHOOL_ID` int(11) NOT NULL,
  `SCHOOL_NAME` varchar(500) DEFAULT NULL,
  `FIRST_DEADLINE` date DEFAULT NULL,
  `SECOND_DEADLINE` date DEFAULT NULL,
  `THIRD_DEADLINE` date DEFAULT NULL,
  `FORTH_DEADLINE` date DEFAULT NULL,
  `AVG_GMAT` int(11) DEFAULT NULL,
  `AVG_TOEFL` int(11) DEFAULT NULL,
  `MEMO` varchar(5000) DEFAULT NULL,
  PRIMARY KEY (`SCHOOL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Info Unique to  School';
